[package]
name = "meilisearch-sdk"
version = "0.7.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"
description = "Rust wrapper for the MeiliSearch API. MeiliSearch is a powerful, fast, open-source, easy to use and deploy search engine."
license = "MIT"
readme  = "README.md"
repository = "https://github.com/meilisearch/meilisearch-sdk"

[dependencies]
serde_json = "1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = "0.3"
isahc = { version = "1.0", features = ["http2", "text-decoding"], default_features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.47"
web-sys = { version = "0.3", features = ["RequestInit", "Headers", "Window", "Response", "console"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[features]
default = ["isahc-static-curl"]
isahc-static-curl = ["isahc/static-curl"]

[dev-dependencies]
env_logger = "0.8"
futures-await-test = "0.3"
futures = "0.3"

# The following dependencies are required for examples
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
yew = "0.17"
web-sys = "0.3"
console_error_panic_hook = "0.1"

[[example]]
name = "web_app"
crate-type = ["cdylib", "rlib"]
path = "examples/web_app/src/lib.rs"
