name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  integration_tests:
    # Will not run if the event is a PR to bump-meilisearch-v* (so a pre-release PR)
    # Will still run for each push to bump-meilisearch-v*
    if: github.event_name != 'pull_request' || !startsWith(github.base_ref, 'bump-meilisearch-v')
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: MeiliSearch (latest version) setup with Docker
      run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --no-analytics=true --master-key=masterKey
    - name: Run tests
      run: cargo test --verbose -- --test-threads=1

  linter:
    name: clippy-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install clippy
      run: rustup component add clippy
    - name: Run linter (clippy)
      # Will fail when encountering warnings
      run: cargo clippy -- -D warnings

  readme_check:
    name: readme-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check the README.md file is up-to-date
      run: sh scripts/check-readme.sh
